[main]
# 终端配色 https://github.com/catppuccin/foot
include=/home/admin/.config/foot/themes/catppuccin-mocha.ini

# 指定主字体为 Noto Sans Mono CJK SC，字号大小设置为 10（根据需要自行调整pt大小）
font=Noto Sans Mono CJK SC:size=10

# 备用/回退字体（可选）：当主字体缺失某些特殊图标/符号时自动补位
font-bold=Noto Sans Mono CJK SC:style=Bold:size=10
font-italic=Noto Sans Mono CJK SC:style=Italic:size=10
font-bold-italic=Noto Sans Mono CJK SC:style=Bold Italic:size=10
