 => ERROR [26/29] RUN . /home/admin/.rvm/scripts/rvm && rvm install 3.3.4 && gem install rails              0.2s
------
 > [26/29] RUN . /home/admin/.rvm/scripts/rvm && rvm install 3.3.4 && gem install rails:
0.153 /bin/sh: 10: /home/admin/.rvm/scripts/rvm: builtin: not found
0.153 /bin/sh: 1: rvm: not found
------
Dockerfile:52
--------------------
  50 |     RUN curl -sSL https://get.rvm.io | bash -s stable
  51 |     # /bin/sh 不支持source，需要使用 . 并且要直接执行rvm，否则每次RUN重新进入/bin/sh会丢失环境
  52 | >>> RUN . /home/admin/.rvm/scripts/rvm && rvm install 3.3.4 && gem install rails
  53 |     # python program: virtualenv
  54 |     RUN python3 -m venv venv3
--------------------
ERROR: failed to solve: process "/bin/sh -c . /home/admin/.rvm/scripts/rvm && rvm install 3.3.4 && gem install rails" did not complete successfully: exit code: 127
