export user=$(id -u -n)
export uid=$(id -u)
export gid=$(id -g)

# multi ports map
podman run -dt --name alpine-dev --hostname alpine-dev \
     -p 1122:1122 \
     -p 8080:8080 \
     -p 8443:8443 \
     -p 9000:9000 \
     -v /home/$user:/home/$user \
     --user $uid:$gid \
     --userns keep-id:uid=$uid,gid=$gid \
     alpine-dev:latest
