#docker build --build-arg USER=$(id -u -n) --build-arg GROUP=$(id -g -n) \
#        --build-arg UID=$(id -u) --build-arg GID=$(id -g) \
docker build --build-arg USER=$(id -u -n) \
        --build-arg UID=$(id -u) \
        -t alpine-dev:latest -f Dockerfile_docker .
