export user=$(id -u -n)
export uid=$(id -u)
export gid=$(id -g)

# multi ports map
# docker run "--user $uid:$gid" same as podman run "--user $uid:$gid --userns keep-id:uid=$uid,gid=$gid"
# lima use "/Users/admin" ,so map "/Users/admin" to docker container's "/home/admin"
docker run -dt --name alpine-dev --hostname alpine-dev \
     -p 1122:1122 \
     -p 8080:8080 \
     -p 8443:8443 \
     -p 9000:9000 \
     -v /Users/admin:/home/$user \
     --user $uid:$gid \
     alpine-dev:latest
