[worker.oci]
enabled = false
env = [
    "HTTP_PROXY=socks5h://192.168.5.2:1080",
    "HTTPS_PROXY=socks5h://192.168.5.2:1080",
    "ALL_PROXY=socks5h://192.168.5.2:1080",
    "NO_PROXY=localhost,127.0.0.1,192.168.5.2"
]

[worker.containerd]
enabled = true
env = [
    "HTTP_PROXY=socks5h://192.168.5.2:1080",
    "HTTPS_PROXY=socks5h://192.168.5.2:1080",
    "ALL_PROXY=socks5h://192.168.5.2:1080",
    "NO_PROXY=localhost,127.0.0.1,192.168.5.2"
]

[grpc]
gid = 1000
