# 我已經全局關閉了GTK和QT支持
#export GTK_IM_MODULE=fcitx
#export QT_IM_MODULE=fcitx

export XMODIFIERS=@im=fcitx

# Enable Wayland support for Mozilla Firefox
export MOZ_ENABLE_WAYLAND=1

# XDG
export XDG_SESSION_TYPE=wayland
