Plugin 'Yggdroot/indentLine'
" 我期望使用默认的 | 作为对齐符号，所以注释掉这行
" let g:indentLine_char = '.'
" 设置多级indentLine使用不同字符
let g:indentLine_char_list = ['|', '¦', '┆', '┊']

" no wrapping
" 我期望自动换行，所以注释掉这行
" set nowrap
