#!/bin/bash
# 这里按照系统实际设备名配置 bldb
# 在MacBook Air 13" Mid 2013 上
bldb='/sys/class/backlight/acpi_video0/brightness'
# 在MacBook Pro 15" Late 2013 上
# bldb='/sys/class/backlight/gmux_backlight/brightness'

# 调节幅度
step=5

current=`cat $bldb`
new=$current
if [ "$1" == "up" ];then
   new=$(($current + $step))
elif [ "$1" == "down" ];then
   new=$(($current - $step))
fi
if [ $new -le 0 ];then
   new=0
fi
echo $new | sudo tee $bldb
current=`cat $bldb`
