" 我的基本设置
" Syntax highlight
syntax enable

" Tabs are spaces
set expandtab
" Number of spaces per tab
set tabstop=4

" Search as soon as characters are entered
set incsearch
" Highlight search results
set hlsearch

set columns=80
set wrapmargin=8
set ruler
