[Service]
Environment="HTTP_PROXY=socks5h://192.168.5.2:1080"
Environment="HTTPS_PROXY=socks5h://192.168.5.2:1080"
Environment="ALL_PROXY=socks5h://192.168.5.2:1080"
Environment="NO_PROXY=localhost,127.0.0.1,192.168.5.2,host.docker.internal"
