#!/usr/bin/env bash

VER='8'
ARCH='x86_64'
REPOS=(BaseOS AppStream extras)

for repoid in ${REPOS[@]}; do
    repo_path="/usr/share/nginx/html/centos/${VER}/${repoid}/${ARCH}/os"

    # After dnf-plugins-core-4.0.14 ,will use "--norepopath"
    #dnf reposync -p ${repo_path} -a x86_64 --newest-only --delete --norepopath --download-metadata --repoid=${repoid}

    # only use before dnf-plugins-core-4.0.14
    dnf reposync -p ${repo_path} -a x86_64 --newest-only --delete --download-metadata --repoid=${repoid} && mv ${repo_path}/${repoid}/* ${repo_path}/ && rm -r ${repo_path}/${repoid}

done
