[sources]
# 1. 填入你通过 ls -l /dev/input/by-id/ 查看到的键盘路径
keyboard = /dev/input/by-id/usb-Apple_Inc._Apple_Internal_Keyboard___Trackpad-event-kbd

# 2. 填入你查看到的触控板路径
mouse = /dev/input/by-id/usb-Apple_Inc._Apple_Internal_Keyboard___Trackpad-if02-event-mouse
