# 激活Homebrew
eval "$(/usr/local/bin/brew shellenv)"

# 在jail中df命令无法获取jail外的目录挂载属性
alias df='df -h 2>/dev/null'

# 设置Locale
export LC_ALL=en_US.UTF-8

# 设置curl代理
# export http_proxy=socks5h://localhost:1080
export http_proxy=http://localhost:3128
export https_proxy=$http_proxy
export no_proxy=localhost,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
