#!/bin/bash
# Disable zswap
echo 0 > /sys/module/zswap/parameters/enabled

# Load zram module
modprobe zram

# use zstd compression
echo zstd > /sys/block/zram0/comp_algorithm

# echo 512M > /sys/block/zram0/disksize
echo 2G > /sys/block/zram0/disksize

mkswap /dev/zram0

# Priority can have values between -1 and 32767
swapon /dev/zram0 -p 32767
