export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway
export INPUT_METHOD=fcitx
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export SDL_IM_MODULE=fcitx
export MOZ_DBUS_REMOTE=1
export GTK_USE_PORTAL=0

# Enable Wayland support for Mozilla Firefox
export MOZ_ENABLE_WAYLAND=1
