syntax on            " 开启语法高亮
set number           " 显示行号
set tabstop=4        " 设置 Tab 宽度为 4
set expandtab        " 将 Tab 自动转为空格 (YAML 文件的刚需)
set cursorline       " 高亮当前行 (方便定位)
set mouse=r          " 禁用鼠标控制，方便在终端进行选择和复制
