FROM debian:latest

ENV container=docker

# 容器内代理设置: 物理服务器上通过SSH Tunnel访问墙外HTTP/HTTPS代理，所以IP地址是Docker的NAT网络网关IP
# 如不需要请注释掉
# 不过我觉得比较灵活的方式还是配置Docker客户端 ~/.docker/config.json
#ENV HTTP_PROXY "http://172.17.0.1:3128"
#ENV HTTP_PROXY "http://172.17.0.1:3128"
#ENV FTP_PROXY "ftp://172.17.0.1:3128"
#ENV NO_PROXY "*.baidu.com,192.168.0.0/16,10.0.0.0/8"

RUN apt clean
RUN apt update -y
RUN apt upgrade -y

# Debian仓库内置tini，可以直接安装
RUN apt -y install tini

# Copy tini entrypoint script
COPY entrypoint_ssh_cron_bash /entrypoint.sh
RUN chmod +x /entrypoint.sh

# SSH
RUN apt -y install sudo passwd openssh-client openssh-server curl
# Utilities
RUN apt -y install cron tmux vim-tiny locales net-tools iproute2 dnsutils plocate gnupg2 git tree unzip lsof wget

# 补全locales
RUN echo "LC_ALL=en_US.UTF-8" >> /etc/environment
RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
RUN echo "LANG=en_US.UTF-8" > /etc/locale.conf
RUN locale-gen en_US.UTF-8

# c program
RUN apt -y install glibc-doc manpages-dev libc6-dev gcc build-essential
# 编译neovim需要
RUN apt -y install cmake gettext
# ruby program install rvm
# python program (debian already inatalled python3)
RUN apt -y install python3.11-venv

RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# add account "admin" and give sudo privilege
RUN groupadd -g 505 admin
RUN useradd -g 505 -u 505 -s /bin/bash -d /home/admin -m admin
RUN adduser admin sudo
RUN echo "%sudo        ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers

# set TIMEZONE to Shanghai
RUN unlink /etc/localtime
RUN ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

RUN mkdir /run/sshd
RUN ssh-keygen -A


USER admin

# ruby program: rvm install ruby in $HOME
RUN gpg2 --keyserver hkp://keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
RUN curl -sSL https://get.rvm.io | bash -s stable
# /bin/sh 不支持source，需要使用 .
# 每个RUN都是一个容器，所以为了继承环境变量来运行多个命令，将这些命令写成一行RUN
# rvm需要使用BASH，所以最终改成 bash -c 'xxx && yyy && zzz'
RUN bash -c 'source /home/admin/.rvm/scripts/rvm && rvm install 3.3.4 && gem install rails'

# 我使用Jekyll构建个人blog，如不需要请注释掉下面一行
# RUN bash -c 'source /home/admin/.bashrc && gem install bundler jekyll'
# 如果报错 "gem: command not found" (我在debian的ARM镜像时遇到)，则改成 "source /home/admin/.rvm/scripts/rvm"
RUN bash -c 'source /home/admin/.rvm/scripts/rvm && gem install bundler jekyll'

# python program: virtualenv
RUN bash -c 'cd /home/admin && python3 -m venv venv3'
# 我使用Sphinx doc来撰写Cloud-Atlas文档，如不需要请注释掉下面两行
RUN bash -c 'source /home/admin/venv3/bin/activate && pip install sphinx && pip install sphinx_rtd_theme && pip install sphinxnotes-strike'
RUN bash -c 'source /home/admin/venv3/bin/activate && pip install sphinxcontrib-video && pip install sphinxcontrib-youtube'

# node program: nvm install node
RUN bash -c "cd /home/admin && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash"
# RUN bash -c "source /home/admin/.bashrc && nvm install 22"
# 如果报错 "nvm: command not found" (在debian的ARM镜像时遇到)，则改成 "source /home/admin/.nvm/nvm.sh" 来加载nvm (参考 ~/.bashrc )
RUN bash -c "source /home/admin/.nvm/nvm.sh && nvm install 22"

# neovim

# 这个步骤是为了解决GFW屏蔽，使用git clone的 over HTTP报错，不得已采用SSH模式，所以会复制密钥，如果直接通过git operations over HTTP工作正常，则不需要这个步骤
# 注意，需要在Dockerfile相同目录下执行 ssh-keygen -t rsa 生成密钥对(私钥不可密码保护)，并将公钥上传到github以便能够git clone

USER admin

#### 接受github的主机认证密钥
#### 可以通过SSH忽略主机密钥 -o StrictHostKeyChecking=no 绕过
## -------------------------------------------------------------
## RUN mkdir /home/admin/.ssh
## RUN ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
## -------------------------------------------------------------

#### 采用git SSH方式
## -------------------------------------------------------------
RUN mkdir /home/admin/src
## COPY 命令复制的文件需要修改属主，否则ssh无法读取
COPY id_rsa /home/admin/src/id_rsa
USER root
RUN chown admin:admin /home/admin/src/id_rsa
USER admin
#### 指定git密钥，这里使用 --global 是因为当前没有在git项目目录下，不用这个参数会报错 "fatal: not in a git directory"
RUN git config --global core.sshCommand 'ssh -i /home/admin/src/id_rsa -o StrictHostKeyChecking=no'
#### git clone使用SSH方式是为了避免GFW干扰，使用git的operation over HTTP在代理模式下存在curl RPC报错
RUN bash -c 'source /home/admin/.bashrc && cd /home/admin/src && git clone git@github.com:neovim/neovim.git && cd /home/admin/src/neovim && make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$HOME/neovim" && make install && echo "export PATH=\"\$HOME/neovim/bin:\$PATH\"" >> /home/admin/.bashrc && echo alias vi=\"\$HOME/neovim/bin/nvim\" >> /home/admin/.bashrc'
RUN bash -c 'cd /home/admin/src && git clone git@github.com:huataihuang/cloud-studio.git && cd /home/admin/src/cloud-studio/config && sh install.sh'
RUN rm -rf /home/admin/src
RUN rm /home/admin/.gitconfig
#### ARM版本debian需要安装clangd以便完成Mason的clangd LSP支持
USER root
RUN apt -y install clangd-16
USER admin
RUN mkdir -p /home/admin/.local/share/nvim/mason/bin
RUN ln -s /usr/bin/clangd-16 /home/admin/.local/share/nvim/mason/bin/clangd
RUN mkdir /home/admin/.local/share/nvim/mason/packages/clangd

#### 使用git operations over HTTP较为简洁，但是会受到网络干扰影响出现 "error: RPC failed; curl 18 Transferred a partial file"
## -------------------------------------------------------------
# RUN bash -c 'mkdir /home/admin/src && source /home/admin/.bashrc && cd /home/admin/src && git clone https://github.com/neovim/neovim.git && cd /home/admin/src/neovim && make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$HOME/neovim" && make install && echo "export PATH=\"\$HOME/neovim/bin:\$PATH\"" >> /home/admin/.bashrc && echo alias vi=\"\$HOME/neovim/bin/nvim\" >> /home/admin/.bashrc'
# RUN bash -c 'cd /home/admin/src && git clone https://github.com/huataihuang/cloud-studio.git && cd /home/admin/src/cloud-studio/config && sh install.sh'
# RUN rm -rf /home/admin/src

# entrypoint.sh 需要使用root身份执行
USER root

# run service when container started - sshd
EXPOSE 22:1122
# Sphinx
EXPOSE 8080:18080
# Jekyll
EXPOSE 4000:14000
# HTTP
EXPOSE 80:1180
# HTTPS
EXPOSE 443:1443

# Run your program under Tini
# CMD ["/your/program", "-and", "-its", "arguments"]
CMD ["/entrypoint.sh"]
