#!/usr//bin/env bash
cluster=z-k8s

cat << EOF > hosts
server-1
server-x
EOF

function gen_cmd() {
    local node=$1
    kubeconfig="--kubeconfig biz/${cluster}/admin.kubeconfig.yaml"

    kubectl ${kubeconfig} get pods -l scheduler.assign/nodename=${node} -A | tee node_pods

    cat node_pods | grep "Terminating" | awk '{print $1" "$2}' | tee node_ns_pods

    while read ns pod; do
        #echo "kubectl ${kubeconfig} -n $ns edit pods $pod" | tee -a node_ns_pods_cmd
        #echo "kubectl ${kubeconfig} -n $ns delete pods $pod --force" | tee -a node_ns_pods_cmd
        echo "kubectl ${kubeconfig} -n $ns patch pods $pod -p '{\"metadata\":{\"finalizers\":null}}' --type=merge" | tee -a node_ns_pods_cmd
    done < "node_ns_pods"
}

function batch_gen_cmd() {
    > node_ns_pods_cmd
    for sn in `cat hosts`;do
        gen_cmd $sn
    done
}

batch_gen_cmd
