sudo bash -c 'cat <<EOF > /etc/modprobe.d/blacklist-nvidia.conf
# 彻底屏蔽 NVIDIA 驱动及其所有子模块
blacklist nvidia
blacklist nvidia_drm
blacklist nvidia_modeset
blacklist nvidia_uvm
blacklist nvidia_modeset
alias nvidia off
alias nvidia_drm off
alias nvidia_modeset off
alias nvidia_uvm off
EOF'
